#!/bin/bash

# Chapter Checker - Complete Setup & Running Guide

echo "═══════════════════════════════════════════════════════════════"
echo "Chapter Checker - Learning Science Analysis Tool"
echo "Vite + React + Tailwind CSS + TypeScript"
echo "═══════════════════════════════════════════════════════════════"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo ""
echo -e "${BLUE}📋 SETUP INSTRUCTIONS${NC}"
echo ""

echo "1️⃣  PREREQUISITES"
echo "   • Node.js v16 or higher"
echo "   • npm v8 or yarn v3"
echo "   • VS Code (recommended)"
echo ""

echo "2️⃣  INSTALLATION"
echo ""
echo -e "${YELLOW}Step A: Install Dependencies${NC}"
echo "   npm install"
echo ""
echo "   This installs:"
echo "   • React 18.2"
echo "   • Vite 5.0"
echo "   • Tailwind CSS 3.3"
echo "   • TypeScript 5.3"
echo "   • Recharts 2.10"
echo ""

echo -e "${YELLOW}Step B: Start Development Server${NC}"
echo "   npm run dev"
echo ""
echo "   This:"
echo "   • Starts dev server on http://localhost:3000"
echo "   • Enables hot module replacement (HMR)"
echo "   • Opens browser automatically"
echo ""

echo -e "${YELLOW}Step C: Open in Browser${NC}"
echo "   • Automatically opens localhost:3000"
echo "   • Paste or upload a chapter"
echo "   • Click 'Analyze Chapter'"
echo ""

echo ""
echo -e "${BLUE}📦 PROJECT STRUCTURE BREAKDOWN${NC}"
echo ""

echo "Root Configuration Files:"
echo "  package.json              - Dependencies & scripts"
echo "  vite.config.ts            - Vite build configuration"
echo "  tailwind.config.ts        - Tailwind CSS theme"
echo "  postcss.config.js         - PostCSS (for Tailwind)"
echo "  tsconfig.json             - TypeScript settings"
echo "  tsconfig.node.json        - TypeScript for build tools"
echo "  index.html                - HTML entry point"
echo ""

echo "Source Directory (src/):"
echo "  main.tsx                  - React app entry point"
echo "  App.tsx                   - Root component"
echo ""
echo "  styles/"
echo "    globals.css             - Global Tailwind CSS"
echo ""
echo "  types/"
echo "    index.ts                - All TypeScript interfaces"
echo ""
echo "  utils/"
echo "    AnalysisEngine.ts       - Analysis logic"
echo ""
echo "  components/"
echo "    ChapterInput/           - Input form section"
echo "      index.tsx"
echo "    Input/                  - Input sub-components"
echo "      TextAreaInput.tsx      - Textarea component"
echo "      FileUploadButton.tsx   - File upload"
echo "      AnalyzeButton.tsx      - Analyze button"
echo "      WordCounter.tsx        - Word count display"
echo "      InfoCard.tsx           - Info cards"
echo "    Alerts/"
echo "      ErrorAlert.tsx         - Error message display"
echo "    Dashboard/              - Results display"
echo "      ChapterAnalysisDashboard.tsx"
echo "      Components/"
echo "        OverallScoreCard.tsx"
echo "        PrincipleScoresGrid.tsx"
echo "        PrincipleScoreCard.tsx"
echo "        ConceptAnalysisSection.tsx"
echo "        RecommendationsSection.tsx"
echo "        RecommendationCard.tsx"
echo ""

echo ""
echo -e "${BLUE}🎯 KEY FILE DESCRIPTIONS${NC}"
echo ""

echo -e "${GREEN}index.html${NC}"
echo "  • HTML entry point for the React app"
echo "  • Includes Google Fonts (Inter)"
echo "  • Mounts React on <div id='root'>"
echo ""

echo -e "${GREEN}src/main.tsx${NC}"
echo "  • React DOM render entry point"
echo "  • Imports global CSS"
echo "  • Mounts App component"
echo ""

echo -e "${GREEN}src/App.tsx${NC}"
echo "  • Root component managing app state"
echo "  • Handles navigation between input/analysis views"
echo "  • Renders header, main content, footer"
echo ""

echo -e "${GREEN}src/types/index.ts${NC}"
echo "  • All TypeScript interfaces and types"
echo "  • Imports: Chapter, Analysis, Recommendation, etc."
echo "  • No runtime code, pure type definitions"
echo ""

echo -e "${GREEN}src/utils/AnalysisEngine.ts${NC}"
echo "  • Orchestrates chapter analysis"
echo "  • Extracts concepts, evaluates principles"
echo "  • Generates recommendations"
echo "  • Returns ChapterAnalysis result"
echo ""

echo -e "${GREEN}src/styles/globals.css${NC}"
echo "  • Global Tailwind CSS configuration"
echo "  • Custom component classes (@layer components)"
echo "  • Base styles (@layer base)"
echo "  • Utility animations"
echo ""

echo ""
echo -e "${BLUE}💻 RUNNING COMMANDS${NC}"
echo ""

echo "Development:"
echo "  npm run dev               - Start dev server (http://localhost:3000)"
echo ""

echo "Production:"
echo "  npm run build             - Build optimized bundle to dist/"
echo "  npm run preview           - Preview production build locally"
echo ""

echo "Code Quality:"
echo "  npm run lint              - Check code style"
echo "  npm run type-check        - Check TypeScript types"
echo ""

echo ""
echo -e "${BLUE}🏗️  COMPONENT ARCHITECTURE${NC}"
echo ""

echo "Props Flow (Parent → Child):"
echo ""
echo "  App"
echo "    ↓"
echo "    ├→ ChapterInput (manage input state)"
echo "    │  ├→ TextAreaInput (controlled input)"
echo "    │  ├→ FileUploadButton (file upload)"
echo "    │  ├→ AnalyzeButton (trigger analysis)"
echo "    │  ├→ WordCounter (display count)"
echo "    │  ├→ InfoCard (display info) × 3"
echo "    │  └→ ErrorAlert (show errors)"
echo "    │"
echo "    └→ ChapterAnalysisDashboard (show results)"
echo "       ├→ OverallScoreCard (display score)"
echo "       ├→ PrincipleScoresGrid (display principles)"
echo "       │  └→ PrincipleScoreCard × 10 (individual scores)"
echo "       ├→ ConceptAnalysisSection (concept stats)"
echo "       ├→ RecommendationsSection (recommendations)"
echo "       │  └→ RecommendationCard × many (individual recs)"
echo "       └→ Export button (export JSON)"
echo ""

echo ""
echo -e "${BLUE}💡 CODE PATTERNS${NC}"
echo ""

echo "Destructuring Props:"
echo "  function MyComponent({ prop1, prop2 }: MyProps): JSX.Element {"
echo "    return <div>{prop1}</div>;"
echo "  }"
echo ""

echo "Props Interface:"
echo "  interface MyComponentProps {"
echo "    /** Description of prop */"
echo "    propName: PropType;"
echo "  }"
echo ""

echo "Component Comments:"
echo "  /**"
echo "   * Component description"
echo "   * Parent: ParentName"
echo "   * Children: ChildNames"
echo "   * @param {Props} props - Component props"
echo "   * @returns {JSX.Element} Description"
echo "   */"
echo ""

echo "Tailwind Classes:"
echo "  btn-primary               - Primary action button"
echo "  btn-secondary             - Secondary button"
echo "  card                      - Card component"
echo "  card-header               - Card header section"
echo "  card-body                 - Card body section"
echo "  input-base                - Base input styling"
echo "  badge-primary             - Primary badge"
echo "  text-gradient             - Gradient text"
echo ""

echo ""
echo -e "${BLUE}📝 ADDING NEW FEATURES${NC}"
echo ""

echo "1. Add new type to src/types/index.ts"
echo "2. Create component in src/components/"
echo "3. Add Props interface with comments"
echo "4. Implement with destructuring"
echo "5. Export default function"
echo "6. Import and use in parent"
echo ""

echo "Example:"
echo "  // src/components/Feature/NewComponent.tsx"
echo "  interface NewComponentProps {"
echo "    /** Prop description */"
echo "    title: string;"
echo "  }"
echo ""
echo "  function NewComponent({ title }: NewComponentProps): JSX.Element {"
echo "    return <div>{title}</div>;"
echo "  }"
echo ""
echo "  export default NewComponent;"
echo ""

echo ""
echo -e "${BLUE}🎨 STYLING GUIDE${NC}"
echo ""

echo "Google Fonts Integration:"
echo "  • Font: Inter (from Google Fonts)"
echo "  • Loaded in index.html"
echo "  • Set as default in tailwind.config.ts"
echo "  • All text uses Inter font"
echo ""

echo "Tailwind Colors:"
echo "  • primary-*               - Gradient purple/indigo"
echo "  • secondary-*             - Blue tones"
echo "  • gray-*                  - Grayscale"
echo "  • Custom in tailwind.config.ts theme.extend.colors"
echo ""

echo "Shadow & Effects:"
echo "  shadow-soft               - Light shadow (cards)"
echo "  shadow-soft-lg            - Medium shadow (hover)"
echo "  shadow-glow               - Glow effect (primary)"
echo "  glass                     - Glassmorphism effect"
echo ""

echo ""
echo -e "${BLUE}🚀 GETTING STARTED CHECKLIST${NC}"
echo ""

echo "✓ Prerequisites installed (Node.js v16+, npm v8+)"
echo "✓ Clone/copy project to local directory"
echo "✓ npm install (installs all dependencies)"
echo "✓ npm run dev (starts dev server)"
echo "✓ Browser opens to localhost:3000"
echo "✓ Try uploading/pasting a chapter"
echo "✓ Click 'Analyze Chapter' button"
echo "✓ View analysis results and recommendations"
echo "✓ Export results as JSON"
echo ""

echo ""
echo -e "${BLUE}📚 PROJECT FILE MANIFEST${NC}"
echo ""

echo "Configuration Files:"
echo "  □ package.json            (290 bytes)"
echo "  □ vite.config.ts          (450 bytes)"
echo "  □ tailwind.config.ts      (1.2 KB)"
echo "  □ postcss.config.js       (80 bytes)"
echo "  □ tsconfig.json           (950 bytes)"
echo "  □ tsconfig.node.json      (250 bytes)"
echo ""

echo "Root Components:"
echo "  □ index.html              (850 bytes)"
echo "  □ src/main.tsx            (290 bytes)"
echo "  □ src/App.tsx             (2.8 KB)"
echo ""

echo "Input Components (ChapterInput):"
echo "  □ src/components/ChapterInput/index.tsx       (4.5 KB)"
echo "  □ src/components/Input/TextAreaInput.tsx      (400 bytes)"
echo "  □ src/components/Input/FileUploadButton.tsx   (550 bytes)"
echo "  □ src/components/Input/AnalyzeButton.tsx      (800 bytes)"
echo "  □ src/components/Input/WordCounter.tsx        (450 bytes)"
echo "  □ src/components/Input/InfoCard.tsx           (500 bytes)"
echo ""

echo "Alert Components:"
echo "  □ src/components/Alerts/ErrorAlert.tsx       (700 bytes)"
echo ""

echo "Dashboard Components:"
echo "  □ src/components/Dashboard/ChapterAnalysisDashboard.tsx  (3.2 KB)"
echo "  □ src/components/Dashboard/Components/OverallScoreCard.tsx    (2.1 KB)"
echo "  □ src/components/Dashboard/Components/PrincipleScoresGrid.tsx (900 bytes)"
echo "  □ src/components/Dashboard/Components/PrincipleScoreCard.tsx  (1.8 KB)"
echo "  □ src/components/Dashboard/Components/ConceptAnalysisSection.tsx (1.5 KB)"
echo "  □ src/components/Dashboard/Components/RecommendationsSection.tsx (1.2 KB)"
echo "  □ src/components/Dashboard/Components/RecommendationCard.tsx     (1.8 KB)"
echo ""

echo "Types & Utils:"
echo "  □ src/types/index.ts                 (8.5 KB)"
echo "  □ src/utils/AnalysisEngine.ts        (3.2 KB)"
echo ""

echo "Styles:"
echo "  □ src/styles/globals.css             (2.8 KB)"
echo ""

echo ""
echo -e "${BLUE}🔗 USEFUL COMMANDS${NC}"
echo ""

echo "First-Time Setup:"
echo "  npm install"
echo "  npm run dev"
echo ""

echo "Development:"
echo "  npm run dev               # Start with HMR"
echo "  npm run type-check        # Check types"
echo "  npm run lint              # Lint code"
echo ""

echo "Production:"
echo "  npm run build             # Optimize & bundle"
echo "  npm run preview           # Preview build"
echo ""

echo "Deployment:"
echo "  # Vercel"
echo "  vercel"
echo ""
echo "  # Netlify (drag dist/ folder)"
echo ""
echo "  # GitHub Pages (configure Actions)"
echo ""

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✨ Ready to code! Start with: npm run dev${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
